### ISSUE TITLE
Dummy-proof reset and leave preview keybinds

### ISSUE THREAD

**Issue by Dworv** [woofdoggo/resetti#10]
If you don't have reset or leave preview keybinds set, Resetti will ignore them and move on, assuming they are the default. Instead, I think it would be a good idea to have it fail to start, explaining that these keybinds need to be set.

Current code:
```go
if keyName == "unknown" {
	continue
}
```

**Comment by Dworv** [comment]
If you agree, I'll make a pull request.

**Comment by woofdoggo** [comment]
I agree, this is a good idea and a PR would be appreciated. I think it probably makes the most sense to return an error from `mc.getInstanceInfo` when the user has Leave Preview or their Atum reset key unbound.

Although we don't currently log any errors from `getInstanceInfo` (we probably should), I think `mc.FindInstances` should be modified to print errors to the console whenever `getInstanceInfo` returns them.

**Comment by Dworv** [comment]
Alright, I'll make a PR.

**Comment by Dworv** [comment]
Actually, it seems like `getInstanceInfo` currently returns an error when the window isn't an instance, and user definitely doesn't need to see all of that. I'll have it return a `bool` in the return tuple that is true when the error is about the instance not being workable and false when the window isn't an instance. If you have an issue with leave, stick it in code review on the PR.

**Comment by woofdoggo** [comment]
Closed by #11
