### ISSUE TITLE
macro didn't work

### ISSUE THREAD

**Issue by Kingnchess** [woofdoggo/resetti#2]
i get this problem when running ./resetti cycle "Failed to open reset count: open : no such file or directory" btw i use arch not sure if that is what messed it up

**Comment by woofdoggo** [comment]
I didn't think to make the reset counting function optional; I'll add that and make a new release. The option `reset-file` in ~/.config/resetti.yml points to where resets should be tracked.

**Comment by woofdoggo** [comment]
Fixed in 00e20dd. You can download the latest version (0.1.3) and it will work without requiring you to specify a reset counter file.
