### ISSUE TITLE
Resetti can't make data folder on its own

### ISSUE THREAD

**Issue by Dworv** [woofdoggo/resetti#9]
When I was trying to start resetti, I kept getting the error "Failed to write resources: access data dir: no such file or directory".

I had to manually create `~/.local/share/resetti` in order to make it run. Surely resetti should be able to do this on its own?

**Comment by woofdoggo** [comment]
This is fixed on the `dev` branch (by `2a1cec7`) but hasn't been included in a release yet.

**Comment by Dworv** [comment]
Good to know, thanks.
